.TH mrrescue 6 "VERSION" "Mr. Rescue"
.SH NAME
mrrescue - Mr. Rescue v VERSION
.SH SYNOPSIS
Arcade-style fire fighting game
.SH DESCRIPTION
Mr. Rescue is an arcade styled 2d action game centered around evacuating
civilians from burning buildings. The game features fast paced fire
extinguishing action, intense boss battles, a catchy soundtrack and lots of
throwing people around in pseudo-randomly generated buildings.
This game is made with LOVE. You can find more games and
information about the author(s) at http://tangramgames.dk/
.SH OPTIONS
.BR \-h ", " \-\-help
Show manpage.
.SH SEE ALSO
.BR love(6)
